/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package PZN_5_Gradle

import com.google.gson.Gson
import module.model.Product
import module.util.StringUtil

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(App().greeting)

    // gradle run
    println("Belajar Kotlin")

    val gson = Gson()

    val product = Product("1", "Handphone Ipun")
    println(StringUtil.toUpper(product.name))
}
